apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wind-wind-turbine-app-dev
  annotations:
    argocd/app-name: wind-wind-turbine-app-dev
    backstage.io/kubernetes-id: wind-wind-turbine-app
    backstage.io/kubernetes-namespace: wind
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-connect/wind-wind-turbine
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-8lznb.l07n.p1.openshiftapps.com/dev-pipelines/ns/wind/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-8lznb.l07n.p1.openshiftapps.com/k8s/ns/wind/deployments/wind-wind-turbine-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-8lznb.l07n.p1.openshiftapps.com/#https://github.com/rhdh-connect/wind-wind-turbine?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ryanj"
